job-service.url=http://job
company-service.url=http://company
review-service.url=http://review

spring.application.name=companyms
server.port=8081
#H2 database
#spring.datasource.url=jdbc:h2:mem:testdb

#Eureka
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone=http://servicereg:8761/eureka/

logging.level.debug=DEBUG

#Rabbitmq
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


#Actuator
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#Zipkin
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0


#POSTGRESQL
spring.datasource.url=jdbc:postgresql://postgres:5432/company
spring.datasource.username=abhi
spring.datasource.password=abhi
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'