job-service.url=http://localhost:8082
company-service.url=http://localhost:8081
review-service.url=http://localhost:8083

spring.application.name=companyms
server.port:8081
#H2 database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=true

#POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/company
spring.datasource.username=abhi
spring.datasource.password=abhi
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'

#Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Zipkin
management.tracing.sampling.probability=1.0

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest